
/*******************************************************************
*
* CAUTION: This file is automatically generated by libgen.
* Version: Xilinx EDK 12.4 EDK_MS4.81d
* DO NOT EDIT.
*
* Copyright (c) 1995-2010 Xilinx, Inc.  All rights reserved.

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xspi.h"

/*
* The configuration table for devices
*/

XSpi_Config XSpi_ConfigTable[] =
{
	{
		XPAR_SPI_DEVICE_ID,
		XPAR_SPI_BASEADDR,
		XPAR_SPI_FIFO_EXIST,
		XPAR_SPI_SPI_SLAVE_ONLY,
		XPAR_SPI_NUM_SS_BITS,
		XPAR_SPI_NUM_TRANSFER_BITS
	}
};


